<?php
// Data kegiatan MI Raudhatul Jannah, satu sumber untuk home.php & kegiatan.php
global $data_kegiatan;
$data_kegiatan = [
  ["img"=>"../images/kegiatan/Pengmas_04.jpg","kategori"=>"HIBAH","judul"=>"PEMBERDAYAAN GURU MI RAUDHATUL JANNAH","deskripsi"=>"Guru-guru MI Raudhatul Jannah mempresentasikan hasil pelatihan pembuatan Google Form, Google Classroom, dan Google Drive yang dipandu oleh Dwi Ade Handayani Capah, S.Kom., M.Kom. Mereka menunjukkan kemampuan baru dalam mengelola kelas digital dan menyusun evaluasi online dengan lebih efektif.","tanggal"=>"5 Juli 2025"],
  ["img"=>"../images/kegiatan/Pengmas_03.jpg","kategori"=>"HIBAH","judul"=>"PEMBERDAYAAN GURU MI RAUDHATUL JANNAH","deskripsi"=>"Pelatihan pembuatan Google Form, Google Classroom, dan Google Drive bersama Dwi Ade Handayani Capah, S.Kom., M.Kom. berjalan lancar. Guru-guru MI Raudhatul Jannah belajar langsung cara membuat kelas digital, menyimpan file di cloud, dan menyusun evaluasi secara online untuk mendukung pembelajaran yang lebih efektif dan modern.","tanggal"=>"4 Juli 2025"],
  ["img"=>"../images/kegiatan/Pengmas_02.jpg","kategori"=>"HIBAH","judul"=>"PEMBERDAYAAN GURU MI RAUDHATUL JANNAH","deskripsi"=>"Guru-guru MI Raudhatul Jannah mempresentasikan hasil pelatihan penggunaan Gemini dan Canva yang telah diberikan. Mereka menunjukkan kreativitas dalam membuat materi ajar digital, sebagai wujud nyata dari implementasi ilmu yang diperoleh selama kegiatan berlangsung.","tanggal"=>"28 Juni 2025"],
  ["img"=>"../images/kegiatan/Pengmas_01.jpg","kategori"=>"HIBAH","judul"=>"PEMBERDAYAAN GURU MI RAUDHATUL JANNAH","deskripsi"=>"Universitas Mercu Buana melalui program hibah PkM kelompok skema pemberdayaan berbasis masyarakat yang didanai oleh DPPM tahun anggaran 2025, mengadakan pelatihan penggunaan Gemini dan Canva untuk pembuatan materi bahan ajar. Kegiatan ini dipandu oleh dosen Hery Derajad Wijaya, S.Kom., MM dan ditujukan bagi para guru MI Raudhatul Jannah.","tanggal"=>"27 Juni 2025"],
];
